# Brewfile — declarative alternative to restore.sh
# Usage: brew bundle --file=Brewfile

# Taps
tap "antoniorodr/memo"
tap "arthur-ficial/tap"
tap "michidk/tools"
tap "openhue/cli"
tap "steipete/tap"
tap "stripe/stripe-cli"
tap "supabase/tap"

# Core tools
brew "git"
brew "gh"
brew "curl"
brew "wget"
brew "ripgrep"
brew "fzf"
brew "z"
brew "autojump"

# Languages & runtimes
brew "node"
brew "nvm"
brew "go"
brew "python@3.13"
brew "python@3.14"
brew "uv"

# JS/TS ecosystem
brew "pnpm"
brew "nx"
brew "typescript"
brew "typescript-language-server"
brew "swc"

# Cloud & infra
brew "cloudflare-wrangler"
brew "supabase"
brew "stripe"
brew "vercel-cli"
brew "tailscale"
brew "caddy"
brew "gnupg"

# Container & dev tools
brew "act"
brew "devcontainer"
brew "docker-completion"
brew "dockerfile-language-server"
brew "vscode-langservers-extracted"
brew "yamllint"
brew "platformio"

# Media & image processing
brew "ffmpeg"
brew "imagemagick"
brew "sox"
brew "whisper-cpp"
brew "openai-whisper"

# ML
brew "mlx"
brew "pytorch"
brew "numpy"

# Custom tap formulae
brew "memo"
brew "gogcli"
brew "goplaces"
brew "himalaya"
brew "imessage-exporter"
brew "imsg"
brew "mcp-publisher"
brew "openhue-cli"
brew "peekaboo"
brew "remindctl"
brew "rmrfrs"
brew "sag"
brew "songsee"
brew "summarize"
brew "svg2png"
brew "vscli"
brew "wacli"
brew "autocode"
brew "gemini-cli"

# Casks
cask "1password"
cask "1password-cli"
cask "arc"
cask "arduino-ide@nightly"
cask "bartender"
cask "betterdisplay"
cask "busycal"
cask "claude"
cask "claude-code"
cask "cloudflare-warp"
cask "codex"
cask "conductor"
cask "container"
cask "cursor-cli"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "figma"
cask "gcloud-cli"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "linear-linear"
cask "orbstack"
cask "postico"
cask "presonus-universal-control"
cask "qmk-toolbox"
cask "raycast"
cask "realvnc-connect"
cask "rotato"
cask "screens-connect"
cask "slack"
cask "sonos"
cask "tailscale-app"
cask "the-unarchiver"
cask "vlc"
cask "whatsapp"
cask "windows-app"
